version: '3.4'

services:
  oblivion2xrm:
    image: oblivion2xrm:latest
    container_name: xrm-server
    mem_limit: 500m
    build:
      context: .
      dockerfile: Dockerfile.linux-image.build
    ports:
    - 6023:6023
