.PHONY: clean All

All:
	@echo "----------Building project:[ xrm-menu-convert - Debug ]----------"
	@"$(MAKE)" -f  "xrm-menu-convert.mk" PreBuild && "$(MAKE)" -f  "xrm-menu-convert.mk"
clean:
	@echo "----------Cleaning project:[ xrm-menu-convert - Debug ]----------"
	@"$(MAKE)" -f  "xrm-menu-convert.mk" clean
