.PHONY: clean All

All:
	@echo "----------Building project:[ xrm-unittest - Debug ]----------"
	@"$(MAKE)" -f  "xrm-unittest.mk" PreBuild && "$(MAKE)" -f  "xrm-unittest.mk"
clean:
	@echo "----------Cleaning project:[ xrm-unittest - Debug ]----------"
	@"$(MAKE)" -f  "xrm-unittest.mk" clean
