.PHONY: clean All

All:
	@echo "----------Building project:[ xrm-server [ARM] - Debug ]----------"
	@"$(MAKE)" -f  "xrm-server.mk"
clean:
	@echo "----------Cleaning project:[ xrm-server [ARM] - Debug ]----------"
	@"$(MAKE)" -f  "xrm-server.mk" clean
