.PHONY: clean All

All:
	@echo "----------Building project:[ xrm-unittest - Debug ]----------"
	@cd "/home/merc/code/Oblivion2-XRM/xrm-unittest" && "$(MAKE)" -f  "xrm-unittest.mk"
clean:
	@echo "----------Cleaning project:[ xrm-unittest - Debug ]----------"
	@cd "/home/merc/code/Oblivion2-XRM/xrm-unittest" && "$(MAKE)" -f  "xrm-unittest.mk" clean
