.PHONY: clean All

All:
	@echo "----------Building project:[ xrm-server - Release ]----------"
	@"$(MAKE)" -f  "xrm-server.mk" PreBuild && "$(MAKE)" -f  "xrm-server.mk"
clean:
	@echo "----------Cleaning project:[ xrm-server - Release ]----------"
	@"$(MAKE)" -f  "xrm-server.mk" clean
